---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    type: ci-cd
spec:
  replicas: 3
  selector:
    matchLabels:
      type: ci-cd
  template:
    metadata:
      name: jenkins-pod
      labels:
        type: ci-cd
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 8080
...
