apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: groundhog2k
  pass_credentials_all: false
  password: ""
  url: https://groundhog2k.github.io/helm-charts/
  username: ""
